# Generated by Django 4.2.7 on 2026-02-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offenders', '0001_initial'),
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Model Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('model_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering'), ('recommender', 'Recommender System'), ('anomaly_detection', 'Anomaly Detection')], max_length=50, verbose_name='Model Type')),
                ('algorithm', models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('decision_tree', 'Decision Tree'), ('svm', 'Support Vector Machine'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('catboost', 'CatBoost'), ('neural_network', 'Neural Network'), ('kmeans', 'K-Means'), ('dbscan', 'DBSCAN')], max_length=50, verbose_name='Algorithm')),
                ('purpose', models.CharField(help_text='What problem does this model solve?', max_length=200, verbose_name='Model Purpose')),
                ('feature_columns', models.JSONField(default=list, verbose_name='Feature Columns')),
                ('target_column', models.CharField(max_length=100, verbose_name='Target Column')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ml_models/trained/%Y/%m/%d/', verbose_name='Model File')),
                ('scaler_file', models.FileField(blank=True, null=True, upload_to='ml_models/scalers/%Y/%m/%d/', verbose_name='Scaler File')),
                ('encoder_file', models.FileField(blank=True, null=True, upload_to='ml_models/encoders/%Y/%m/%d/', verbose_name='Encoder File')),
                ('hyperparameters', models.JSONField(default=dict, verbose_name='Hyperparameters')),
                ('training_parameters', models.JSONField(default=dict, verbose_name='Training Parameters')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Accuracy')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='Precision')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='Recall')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='F1 Score')),
                ('mse', models.FloatField(blank=True, null=True, verbose_name='Mean Squared Error')),
                ('rmse', models.FloatField(blank=True, null=True, verbose_name='Root Mean Squared Error')),
                ('r2_score', models.FloatField(blank=True, null=True, verbose_name='R² Score')),
                ('auc_roc', models.FloatField(blank=True, null=True, verbose_name='AUC-ROC Score')),
                ('confusion_matrix', models.JSONField(default=dict, verbose_name='Confusion Matrix')),
                ('feature_importance', models.JSONField(default=dict, verbose_name='Feature Importance')),
                ('status', models.CharField(choices=[('training', 'Training'), ('trained', 'Trained'), ('validating', 'Validating'), ('deployed', 'Deployed'), ('error', 'Error'), ('retired', 'Retired')], default='training', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Model')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_trained', models.DateTimeField(auto_now=True, verbose_name='Last Trained')),
                ('deployed_at', models.DateTimeField(blank=True, null=True, verbose_name='Deployed At')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Version')),
                ('training_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Training Time (seconds)')),
                ('model_size_kb', models.FloatField(blank=True, null=True, verbose_name='Model Size (KB)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('parent_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_models', to='ml_models.mlmodel', verbose_name='Parent Model')),
                ('trained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_ml_models', to=settings.AUTH_USER_MODEL, verbose_name='Trained By')),
                ('training_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to='datasets.dataset', verbose_name='Training Dataset')),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True, verbose_name='Job ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('parameters', models.JSONField(default=dict, verbose_name='Training Parameters')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Progress Percentage')),
                ('current_step', models.CharField(blank=True, max_length=100, verbose_name='Current Step')),
                ('metrics', models.JSONField(default=dict, verbose_name='Training Metrics')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('output_log', models.TextField(blank=True, verbose_name='Output Log')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('cpu_usage', models.FloatField(blank=True, null=True, verbose_name='CPU Usage (%)')),
                ('memory_usage_mb', models.FloatField(blank=True, null=True, verbose_name='Memory Usage (MB)')),
                ('training_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Training Time (seconds)')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.dataset', verbose_name='Dataset')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='ml_models.mlmodel', verbose_name='ML Model')),
            ],
            options={
                'verbose_name': 'Training Job',
                'verbose_name_plural': 'Training Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_features', models.JSONField(default=dict, verbose_name='Input Features')),
                ('prediction_result', models.JSONField(default=dict, verbose_name='Prediction Result')),
                ('prediction_confidence', models.FloatField(blank=True, null=True, verbose_name='Prediction Confidence')),
                ('predicted_class', models.CharField(blank=True, max_length=100, verbose_name='Predicted Class')),
                ('predicted_value', models.FloatField(blank=True, null=True, verbose_name='Predicted Value')),
                ('prediction_time', models.DateTimeField(auto_now_add=True, verbose_name='Prediction Time')),
                ('batch_id', models.CharField(blank=True, max_length=100, verbose_name='Batch ID')),
                ('actual_value', models.FloatField(blank=True, null=True, verbose_name='Actual Value')),
                ('actual_class', models.CharField(blank=True, max_length=100, verbose_name='Actual Class')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Prediction Correct')),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Made By')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_models.mlmodel', verbose_name='ML Model')),
                ('offender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_predictions', to='offenders.offender', verbose_name='Offender')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['-prediction_time'],
            },
        ),
    ]
