# Generated by Django 4.2.7 on 2026-02-08 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0, verbose_name='X Position')),
                ('position_y', models.IntegerField(default=0, verbose_name='Y Position')),
                ('width', models.IntegerField(default=6, verbose_name='Width (columns)')),
                ('height', models.IntegerField(default=4, verbose_name='Height (rows)')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Custom Title')),
                ('show_title', models.BooleanField(default=True, verbose_name='Show Title')),
                ('refresh_interval', models.IntegerField(blank=True, null=True, verbose_name='Refresh Interval (seconds)')),
                ('parameters', models.JSONField(default=dict, verbose_name='Report Parameters')),
            ],
            options={
                'verbose_name': 'Dashboard Report',
                'verbose_name_plural': 'Dashboard Reports',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Report Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('generation_date', models.DateTimeField(auto_now_add=True, verbose_name='Generation Date')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Report File')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML'), ('json', 'JSON')], max_length=20, verbose_name='File Format')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('parameters', models.JSONField(default=dict, verbose_name='Generation Parameters')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], default='generating', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('generation_time', models.FloatField(default=0, verbose_name='Generation Time (seconds)')),
                ('download_count', models.IntegerField(default=0, verbose_name='Download Count')),
                ('last_downloaded', models.DateTimeField(blank=True, null=True, verbose_name='Last Downloaded')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-generation_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Report Type Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('compliance', 'Compliance'), ('performance', 'Performance'), ('operational', 'Operational'), ('analytical', 'Analytical'), ('statistical', 'Statistical'), ('custom', 'Custom')], default='compliance', max_length=50, verbose_name='Category')),
                ('is_daily', models.BooleanField(default=False, verbose_name='Available Daily')),
                ('is_weekly', models.BooleanField(default=False, verbose_name='Available Weekly')),
                ('is_monthly', models.BooleanField(default=True, verbose_name='Available Monthly')),
                ('is_quarterly', models.BooleanField(default=False, verbose_name='Available Quarterly')),
                ('is_yearly', models.BooleanField(default=True, verbose_name='Available Yearly')),
                ('allowed_roles', models.JSONField(default=list, help_text='List of user roles allowed to generate this report', verbose_name='Allowed User Roles')),
                ('template_path', models.CharField(blank=True, help_text='Path to report template file', max_length=200, verbose_name='Template Path')),
                ('parameters_schema', models.JSONField(default=dict, help_text='JSON schema for report parameters', verbose_name='Parameters Schema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Report Type',
                'verbose_name_plural': 'Report Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('template_file', models.FileField(help_text='HTML or other template file', upload_to='report_templates/', verbose_name='Template File')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Version')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Template')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('report_types', models.ManyToManyField(related_name='templates', to='reports.reporttype', verbose_name='Applicable Report Types')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Schedule Name')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Frequency')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for indefinite schedule', null=True, verbose_name='End Date')),
                ('scheduled_time', models.TimeField(default='09:00', help_text='Time of day to generate the report', verbose_name='Scheduled Time')),
                ('send_email', models.BooleanField(default=True, verbose_name='Send via Email')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='Email Subject')),
                ('email_message', models.TextField(blank=True, verbose_name='Email Message')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('error', 'Error')], default='active', max_length=20, verbose_name='Status')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Next Run')),
                ('parameters', models.JSONField(default=dict, verbose_name='Report Parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('recipients', models.ManyToManyField(help_text='Users who will receive this report', related_name='report_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttype', verbose_name='Report Type')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dashboard Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('layout_config', models.JSONField(default=dict, help_text='JSON configuration for dashboard layout', verbose_name='Layout Configuration')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public Dashboard')),
                ('refresh_interval', models.IntegerField(default=300, help_text='Auto-refresh interval in seconds', verbose_name='Refresh Interval (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Allowed Users')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('reports', models.ManyToManyField(through='reports.DashboardReport', to='reports.reporttype', verbose_name='Included Reports')),
            ],
            options={
                'verbose_name': 'Report Dashboard',
                'verbose_name_plural': 'Report Dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('shared', 'Shared'), ('printed', 'Printed'), ('emailed', 'Emailed')], max_length=20, verbose_name='Action')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='Action Time')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='Session ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='reports.generatedreport', verbose_name='Report')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Report Analytics',
                'verbose_name_plural': 'Report Analytics',
                'ordering': ['-action_time'],
            },
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reporttype', verbose_name='Report Type'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reportschedule', verbose_name='Scheduled Report'),
        ),
        migrations.AddField(
            model_name='dashboardreport',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportdashboard', verbose_name='Dashboard'),
        ),
        migrations.AddField(
            model_name='dashboardreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttype', verbose_name='Report Type'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardreport',
            unique_together={('dashboard', 'report_type')},
        ),
    ]
