# Generated by Django 6.0.2 on 2026-02-08 08:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offender_id', models.CharField(max_length=20, unique=True, verbose_name='Offender ID')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('nationality', models.CharField(default='Kenyan', max_length=100, verbose_name='Nationality')),
                ('id_number', models.CharField(help_text='Kenyan National ID or Passport', max_length=20, unique=True, verbose_name='National ID Number')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=20, verbose_name='Risk Level')),
                ('ml_risk_score', models.FloatField(blank=True, help_text='AI-predicted risk score (0-1)', null=True, verbose_name='ML Risk Score')),
                ('address', models.TextField(verbose_name='Physical Address')),
                ('county', models.CharField(max_length=100, verbose_name='County')),
                ('sub_county', models.CharField(max_length=100, verbose_name='Sub-County')),
                ('phone_alternative', models.CharField(blank=True, max_length=15, verbose_name='Alternative Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(max_length=15, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_relationship', models.CharField(max_length=50, verbose_name='Relationship')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offender_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Offender',
                'verbose_name_plural': 'Offenders',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='Case Number')),
                ('court_name', models.CharField(max_length=200, verbose_name='Court Name')),
                ('court_location', models.CharField(max_length=200, verbose_name='Court Location')),
                ('offense', models.CharField(max_length=300, verbose_name='Offense Committed')),
                ('offense_category', models.CharField(choices=[('property', 'Property Crime'), ('violent', 'Violent Crime'), ('drug', 'Drug Offense'), ('traffic', 'Traffic Violation'), ('financial', 'Financial Crime'), ('other', 'Other')], max_length=100, verbose_name='Offense Category')),
                ('offense_date', models.DateField(verbose_name='Date of Offense')),
                ('sentence_start', models.DateField(verbose_name='Sentence Start Date')),
                ('sentence_end', models.DateField(verbose_name='Sentence End Date')),
                ('sentence_duration', models.IntegerField(verbose_name='Sentence Duration (months)')),
                ('sentence_type', models.CharField(choices=[('probation', 'Probation'), ('community_service', 'Community Service'), ('parole', 'Parole'), ('conditional_release', 'Conditional Release')], max_length=50, verbose_name='Sentence Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('violated', 'Probation Violated'), ('transferred', 'Transferred')], default='active', max_length=20, verbose_name='Case Status')),
                ('special_conditions', models.TextField(blank=True, help_text='Any special conditions or restrictions', verbose_name='Special Conditions')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('probation_officer', models.ForeignKey(limit_choices_to={'role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Probation Officer')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='offenders.offender', verbose_name='Offender')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(verbose_name='Assessment Date')),
                ('criminal_history', models.IntegerField(help_text='Number of prior offenses (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Criminal History Score')),
                ('education_level', models.IntegerField(choices=[(1, 'No Formal Education'), (2, 'Primary'), (3, 'Secondary'), (4, 'Diploma'), (5, 'Degree/Higher')], verbose_name='Education Level')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('casual', 'Casual Laborer')], max_length=50, verbose_name='Employment Status')),
                ('employment_duration', models.IntegerField(default=0, help_text='0 if unemployed', verbose_name='Employment Duration (months)')),
                ('substance_abuse', models.BooleanField(default=False, verbose_name='Substance Abuse History')),
                ('mental_health_issues', models.BooleanField(default=False, verbose_name='Mental Health Issues')),
                ('anger_issues', models.BooleanField(default=False, verbose_name='Anger Management Issues')),
                ('family_support', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], verbose_name='Family Support')),
                ('peer_support', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], verbose_name='Peer Support')),
                ('community_ties', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], verbose_name='Community Ties')),
                ('financial_stability', models.IntegerField(choices=[(1, 'Very Unstable'), (2, 'Unstable'), (3, 'Moderate'), (4, 'Stable'), (5, 'Very Stable')], verbose_name='Financial Stability')),
                ('housing_stability', models.IntegerField(choices=[(1, 'Very Unstable'), (2, 'Unstable'), (3, 'Moderate'), (4, 'Stable'), (5, 'Very Stable')], verbose_name='Housing Stability')),
                ('overall_risk_score', models.FloatField(blank=True, help_text='Calculated risk score (0-100)', null=True, verbose_name='Overall Risk Score')),
                ('recommended_interventions', models.TextField(blank=True, verbose_name='Recommended Interventions')),
                ('notes', models.TextField(blank=True, verbose_name='Assessment Notes')),
                ('assessed_by', models.ForeignKey(limit_choices_to={'role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assessed By')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='offenders.offender', verbose_name='Offender')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
    ]
