# Generated by Django 4.2.7 on 2026-02-08 13:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Program Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('program_type', models.CharField(choices=[('vocational', 'Vocational Training'), ('educational', 'Educational'), ('counseling', 'Counseling'), ('life_skills', 'Life Skills'), ('substance_abuse', 'Substance Abuse'), ('anger_management', 'Anger Management'), ('other', 'Other')], max_length=50, verbose_name='Program Type')),
                ('objectives', models.TextField(verbose_name='Program Objectives')),
                ('curriculum', models.TextField(blank=True, verbose_name='Curriculum Outline')),
                ('duration_weeks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(104)], verbose_name='Duration (weeks)')),
                ('hours_per_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Hours per Week')),
                ('max_participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Participants')),
                ('eligibility_criteria', models.TextField(blank=True, verbose_name='Eligibility Criteria')),
                ('target_risk_level', models.CharField(choices=[('all', 'All Risk Levels'), ('low', 'Low Risk Only'), ('medium', 'Medium Risk Only'), ('high', 'High Risk Only'), ('low_medium', 'Low & Medium Risk'), ('medium_high', 'Medium & High Risk')], default='all', max_length=20, verbose_name='Target Risk Level')),
                ('facilitator_notes', models.TextField(blank=True, verbose_name='Facilitator Notes')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('schedule_description', models.TextField(help_text='E.g., Mondays & Wednesdays, 2-4 PM', verbose_name='Schedule Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('cost_per_participant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost per Participant')),
                ('resources_required', models.TextField(blank=True, verbose_name='Resources Required')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('draft', 'Draft')], default='draft', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Program')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='fas fa-graduation-cap', help_text='Font Awesome icon class', max_length=50)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class', max_length=20)),
            ],
            options={
                'verbose_name': 'Program Category',
                'verbose_name_plural': 'Program Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(verbose_name='Session Number')),
                ('title', models.CharField(max_length=200, verbose_name='Session Title')),
                ('description', models.TextField(verbose_name='Session Description')),
                ('learning_objectives', models.TextField(blank=True, verbose_name='Learning Objectives')),
                ('date', models.DateField(verbose_name='Session Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('materials_required', models.TextField(blank=True, verbose_name='Materials Required')),
                ('reference_materials', models.TextField(blank=True, verbose_name='Reference Materials')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Session Completed')),
                ('completion_notes', models.TextField(blank=True, verbose_name='Completion Notes')),
                ('facilitator', models.ForeignKey(limit_choices_to={'role__in': ['officer', 'ngo']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Facilitator')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='programs.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['program', 'session_number'],
                'unique_together': {('program', 'session_number')},
            },
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.programcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='program',
            name='co_facilitator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['officer', 'ngo']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_facilitated_programs', to=settings.AUTH_USER_MODEL, verbose_name='Co-Facilitator'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='program',
            name='facilitator',
            field=models.ForeignKey(limit_choices_to={'role__in': ['officer', 'ngo']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_programs', to=settings.AUTH_USER_MODEL, verbose_name='Facilitator'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='Enrollment Date')),
                ('referral_notes', models.TextField(blank=True, verbose_name='Referral Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('completed', 'Completed'), ('dropped_out', 'Dropped Out'), ('transferred', 'Transferred'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='Status')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Actual Start Date')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Actual End Date')),
                ('attendance_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Attendance Rate (%)')),
                ('participation_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Participation Score (0-10)')),
                ('skill_improvement', models.TextField(blank=True, verbose_name='Skill Improvement Assessment')),
                ('completion_grade', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement'), ('incomplete', 'Incomplete')], max_length=30, verbose_name='Completion Grade')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Certificate Issued')),
                ('certificate_issue_date', models.DateField(blank=True, null=True, verbose_name='Certificate Issue Date')),
                ('progress_notes', models.TextField(blank=True, verbose_name='Progress Notes')),
                ('facilitator_feedback', models.TextField(blank=True, verbose_name='Facilitator Feedback')),
                ('officer_feedback', models.TextField(blank=True, verbose_name='Probation Officer Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to='offenders.offender', verbose_name='Offender')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='programs.program', verbose_name='Program')),
                ('referred_by', models.ForeignKey(limit_choices_to={'role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Referred By')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('program', 'offender')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absence'), ('left_early', 'Left Early')], max_length=20, verbose_name='Attendance Status')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-in Time')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('participation_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Participation Score (0-10)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='programs.enrollment', verbose_name='Enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='programs.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'unique_together': {('session', 'enrollment')},
            },
        ),
    ]
