# Generated by Django 6.0.3 on 2026-03-18 19:02

from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify


def populate_programcategory_fields(apps, schema_editor):
    ProgramCategory = apps.get_model("programs", "ProgramCategory")

    now = timezone.now()
    existing_slugs = set(
        ProgramCategory.objects.exclude(slug__isnull=True).exclude(slug="").values_list("slug", flat=True)
    )

    for category in ProgramCategory.objects.all().only("id", "name", "slug", "created_at", "updated_at"):
        changed = False

        if not category.created_at:
            category.created_at = now
            changed = True
        if not category.updated_at:
            category.updated_at = now
            changed = True

        if not category.slug:
            base = slugify(category.name)[:110] or f"category-{category.id}"
            slug = base
            i = 2
            while slug in existing_slugs:
                suffix = f"-{i}"
                slug = f"{base[: (120 - len(suffix))]}{suffix}"
                i += 1
            category.slug = slug
            existing_slugs.add(slug)
            changed = True

        if changed:
            category.save(update_fields=["slug", "created_at", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Program Category', 'verbose_name_plural': 'Program Categories'},
        ),
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, help_text='Optional short code, e.g., VTC-001', max_length=30, null=True, unique=True, verbose_name='Program Code'),
        ),
        migrations.AddField(
            model_name='program',
            name='completion_criteria',
            field=models.TextField(blank=True, verbose_name='Completion Criteria'),
        ),
        migrations.AddField(
            model_name='program',
            name='delivery_method',
            field=models.CharField(choices=[('in_person', 'In-Person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='in_person', max_length=20, verbose_name='Delivery Method'),
        ),
        migrations.AddField(
            model_name='program',
            name='enrollment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Enrollment Deadline'),
        ),
        migrations.AddField(
            model_name='program',
            name='expected_outcomes',
            field=models.TextField(blank=True, verbose_name='Expected Outcomes'),
        ),
        migrations.AddField(
            model_name='program',
            name='prerequisites',
            field=models.TextField(blank=True, verbose_name='Prerequisites'),
        ),
        migrations.AddField(
            model_name='program',
            name='referral_required',
            field=models.BooleanField(default=False, verbose_name='Referral Required'),
        ),
        migrations.AddField(
            model_name='programcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='programcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='programcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='programcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Optional. Auto-generated from name if blank.', max_length=120, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='programcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.RunPython(populate_programcategory_fields, migrations.RunPython.noop),
    ]
