# Generated by Django 6.0.3 on 2026-03-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_programcategory_options_program_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='custom', help_text='General cadence; use schedule description for specifics.', max_length=20, verbose_name='Frequency'),
        ),
    ]
